dist: bionic
sudo: false

language: c++

compiler:
  - gcc

addons:
  apt:
    packages:
      - libelf-dev
  coverity_scan:
    project:
      name: "janweinstock/vcml"
      description: "A modeling library with virtual components for SystemC and TLM simulators"
    notification_email: jan.weinstock@rwth-aachen.de
    build_command: make
    branch_pattern: coverity

cache:
  directories:
    - DEPENDS

env:
  global:
    - secure: "tb2yzI9qiysUWPbE/EE39/NxRG155Ga2/6Gptp8yXbu7xo1pl80Bp/6luZUuRhgU1XWy8Vhmq7ww8LsHz1ZwiWpXn4tbBrCrXqAeic0bfSCr3QxNKGY2F108XTDC4/GdgyGvzpJsS3w+t5EaXP/o4io+jveMjkNOYXE276d/TzaOTc+WvlydSgvs/ErusNfUCXoD+FhdyUpDkZpt6LchhlgdDC2XJO4/CrTJLP81U3g/2lpp5g59f9QR4s0sIBuAVnTCtoYzOUC11clwmFXgUfLaLV5ALTsP4e+nQPD6b2kyrJOKSJbVgaO404dhvWOl8QYE547GYarxvUdYZC0os9MfLq/uKO51uBphft2/6f7FrZDKG2T6n1nvnefNq2tya19DhWipzFlEC+c8SQUTuue5kHNltHibHU6DQJbvet5wSrlKXpjGw6pmRi3DsnepefAzues5OVxyuZOhB/odTtZkX8MsKOcREiEKMlIl5OXkWQxNF2P8Of7hF/Wbq1KRtXVnwYXpUiD9QJuVCrxTdqJ83fAGlafQIZomzVzdRtw1sQYT+jSfYFUgxtB7RHOiXBZGb5RzR9EvuSfObFMmLz5p5aD5LvQm3ffYLwNoABc6omR9DCUrmPkf/LazTclhIzWian+ERj12/Mi/8pnlFLwBNnAxXO0JOkBxvMenyvw="
  jobs:
    - BUILD=RELEASE TARGET_ARCH=linux64 SYSTEMC=systemc-2.3.0a
    - BUILD=RELEASE TARGET_ARCH=linux64 SYSTEMC=systemc-2.3.1a
    - BUILD=RELEASE TARGET_ARCH=linux64 SYSTEMC=systemc-2.3.2

install:
  - mkdir -p DEPENDS && cd DEPENDS
  - export SYSTEMC_HOME=`pwd`/$SYSTEMC
  - | # Build SystemC
      if [ ! -d $SYSTEMC_HOME ]; then
          wget http://www.accellera.org/images/downloads/standards/systemc/$SYSTEMC.tar.gz
          tar -xzf $SYSTEMC.tar.gz && cd $SYSTEMC
          mkdir BUILD && cd BUILD
          ../configure --enable-static CXXFLAGS="-std=c++11"
          make -j 4 && make install
          cd ../..
          rm -rf $SYSTEMC.tar.gz $SYSTEMC/BUILD
      fi
  - export GTEST_ROOT=`pwd`/googletest-release-1.8.0/INSTALL
  - export GMOCK_ROOT=$GTEST_ROOT
  - | # Build Google Test
      if [ ! -d $GTEST_ROOT ]; then
          wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
          tar -xzf release-1.8.0.tar.gz && cd googletest-release-1.8.0
          mkdir BUILD && cd BUILD
          cmake .. -DCMAKE_INSTALL_PREFIX=$GTEST_ROOT -DCMAKE_CXX_STANDARD=11
          make -j 4 && make install
          cd ../..
          rm -rf release-1.8.0.tar.gz googletest-release-1.8.0/BUILD
      fi
  - cd ..

before_script:
  - mkdir BUILD && cd BUILD
  - cmake .. -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=$BUILD

script:
  - make -j 4 && ctest --output-on-failure

